// fileTemplates/extensions/ReduxExtension/Angular/src/app/counter/counter.component.ts
import { Component } from '@angular/core'
import { StoreService } from '../services/store.service'
import { map } from 'rxjs/operators'
import {
  decrement,
  increment,
  incrementAsync,
  incrementByAmount,
  incrementIfOdd,
  selectCount,
} from '../services/counterSlice'

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.css'],
})
export class CounterComponent {
  count$ = this.store.state$.pipe(map(selectCount))
  incrementAmount = 2

  constructor(private store: StoreService) {}

  increment() {
    this.store.dispatch(increment())
  }

  decrement() {
    this.store.dispatch(decrement())
  }

  incrementAsync() {
    this.store.dispatch(incrementAsync(this.incrementAmount))
  }

  incrementIfOdd() {
    this.store.dispatch(incrementIfOdd(this.incrementAmount))
  }

  incrementByAmount() {
    this.store.dispatch(incrementByAmount(this.incrementAmount))
  }
}

<h2>Counter</h2>
<div>
  <div class="row">
    <button (click)="decrement()">-</button>
    <span class="value">{{ count$ | async }}</span>
    <button (click)="increment()">+</button>
  </div>
  <div class="row">
    <input type="number" [(ngModel)]="incrementAmount" />
    <button (click)="incrementByAmount()">Add amount</button>
    <button (click)="incrementAsync()" class="asyncButton">Add async</button>
    <button (click)="incrementIfOdd()">Add if odd</button>
  </div>
</div>

// fileTemplates/extensions/ReduxExtension/src/features/counter/Counter.tsx
import React, { useState } from 'react'
import { useAppDispatch, useAppSelector } from '../../app/hooks'
import {
  decrement,
  increment,
  incrementAsync,
  incrementByAmount,
  incrementIfOdd,
  selectCount,
} from './counterSlice'
import './Counter.css'

export const Counter = () => {
  const count = useAppSelector(selectCount)
  const dispatch = useAppDispatch()
  const [incrementAmount, setIncrementAmount] = useState('2')

  const incrementValue = Number(incrementAmount) ?? 0

  return (
    <div>
      <div className={'row'}>
        <button
          className={'button'}
          aria-label="Decrement value"
          onClick={() => dispatch(decrement())}
        >
          -
        </button>
        <span className={'value'}>{count}</span>
        <button
          className={'button'}
          aria-label="Increment value"
          onClick={() => dispatch(increment())}
        >
          +
        </button>
      </div>
      <div className={'row'}>
        <input
          className={'textbox'}
          aria-label="Set increment amount"
          value={incrementAmount}
          onChange={(e) => setIncrementAmount(e.target.value)}
        />
        <button
          className={'button'}
          onClick={() => dispatch(incrementByAmount(incrementValue))}
        >
          Add Amount
        </button>
        <button
          className={'asyncButton'}
          onClick={() => dispatch(incrementAsync(incrementValue))}
        >
          Add Async
        </button>
        <button
          className={'button'}
          onClick={() => dispatch(incrementIfOdd(incrementValue))}
        >
          Add If Odd
        </button>
      </div>
    </div>
  )
}
